# 🦊 SoranaOS - Hyprlock Sanctuary 💠

general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =
    path = /home/void/.config/swww/wallpaper.png   # Твои любимые обои
    color = rgba(26, 29, 54, 1.0) # Soft Midnight Indigo
    blur_passes = 2
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

# Часы
label {
    monitor =
    text = $TIME
    color = #e0d4d4 # Ash Pink
    font_size = 120
    font_family = JetBrainsMono Nerd Font Bold
    position = 0, -140
    halign = center
    valign = top
}

# Приветствие
label {
    monitor =
    text = Hello, my dear Void... 🦊
    color = #00bfa5 # Emerald
    font_size = 25
    font_family = JetBrainsMono Nerd Font
    position = 0, -40
    halign = center
    valign = center
}

# Поле ввода пароля
input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgba(0, 191, 165, 1.0) # Emerald
    inner_color = rgba(9, 10, 20, 0.8) # Void Indigo
    font_color = #e0d4d4 # Ash Pink
    fade_on_empty = true
    placeholder_text = <i>Password...</i>
    hide_input = false
    position = 0, -120
    halign = center
    valign = center
}
